### PR TITLE
Organize libs

### PR DESCRIPTION
**Pull request by ChelloX**
Habe alle lokalen Jars in das Maven-Repo in CommonLibs geschoben.

### CODE REVIEW

**Review by tfreytag — CHANGES_REQUESTED** [review]
JAR mit Dependencies kann ich erstellen, auch der Mac-Installer kann erfolgreich gebaut werden. Fehlende Funktionen aus internen JARs sind dabei, scheint alles ok.
Aber leider bricht das Bauen des Windows-Installers vorzeitig ab in Maven.
[ERROR] Failed to execute goal org.codehaus.izpack:izpack-maven-plugin:5.0.9:izpack (default) on project WoPeD-IzPack: Execution default of goal org.codehaus.izpack:izpack-maven-plugin:5.0.9:izpack failed: A required class was missing while executing org.codehaus.izpack:izpack-maven-plugin:5.0.9:izpack: java/util/jar/Pack200
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.izpack:izpack-maven-plugin:5.0.9
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-maven-plugin/5.0.9/izpack-maven-plugin-5.0.9.jar
[ERROR] urls[1] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-panel/5.0.9/izpack-panel-5.0.9.jar
[ERROR] urls[2] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-tools/5.0.9/izpack-tools-5.0.9.jar
[ERROR] urls[3] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-util/5.0.9/izpack-util-5.0.9.jar
[ERROR] urls[4] = file:/Users/freytag/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
[ERROR] urls[5] = file:/Users/freytag/.m2/repository/org/jdom/jdom2/2.0.5/jdom2-2.0.5.jar
[ERROR] urls[6] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-installer/5.0.9/izpack-installer-5.0.9.jar
[ERROR] urls[7] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-gui/5.0.9/izpack-gui-5.0.9.jar
[ERROR] urls[8] = file:/Users/freytag/.m2/repository/org/picocontainer/picocontainer/2.14.1/picocontainer-2.14.1.jar
[ERROR] urls[9] = file:/Users/freytag/.m2/repository/org/apache/pdfbox/pdfbox/1.8.10/pdfbox-1.8.10.jar
[ERROR] urls[10] = file:/Users/freytag/.m2/repository/org/apache/pdfbox/fontbox/1.8.10/fontbox-1.8.10.jar
[ERROR] urls[11] = file:/Users/freytag/.m2/repository/org/apache/pdfbox/jempbox/1.8.10/jempbox-1.8.10.jar
[ERROR] urls[12] = file:/Users/freytag/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ERROR] urls[13] = file:/Users/freytag/.m2/repository/org/icepdf/os/icepdf-core/6.0.1/icepdf-core-6.0.1.jar
[ERROR] urls[14] = file:/Users/freytag/.m2/repository/javax/media/jai-core/1.1.3/jai-core-1.1.3.jar
[ERROR] urls[15] = file:/Users/freytag/.m2/repository/com/sun/media/jai_imageio/1.1/jai_imageio-1.1.pom
[ERROR] urls[16] = file:/Users/freytag/.m2/repository/org/icepdf/os/icepdf-viewer/6.0.1/icepdf-viewer-6.0.1.jar
[ERROR] urls[17] = file:/Users/freytag/.m2/repository/batik/batik-awt-util/1.6/batik-awt-util-1.6.jar
[ERROR] urls[18] = file:/Users/freytag/.m2/repository/batik/batik-dom/1.6/batik-dom-1.6.jar
[ERROR] urls[19] = file:/Users/freytag/.m2/repository/batik/batik-svg-dom/1.6/batik-svg-dom-1.6.jar
[ERROR] urls[20] = file:/Users/freytag/.m2/repository/batik/batik-svggen/1.6/batik-svggen-1.6.jar
[ERROR] urls[21] = file:/Users/freytag/.m2/repository/batik/batik-util/1.6/batik-util-1.6.jar
[ERROR] urls[22] = file:/Users/freytag/.m2/repository/batik/batik-xml/1.6/batik-xml-1.6.jar
[ERROR] urls[23] = file:/Users/freytag/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar
[ERROR] urls[24] = file:/Users/freytag/.m2/repository/org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar
[ERROR] urls[25] = file:/Users/freytag/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar
[ERROR] urls[26] = file:/Users/freytag/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
[ERROR] urls[27] = file:/Users/freytag/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
[ERROR] urls[28] = file:/Users/freytag/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
[ERROR] urls[29] = file:/Users/freytag/.m2/repository/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
[ERROR] urls[30] = file:/Users/freytag/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[31] = file:/Users/freytag/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
[ERROR] urls[32] = file:/Users/freytag/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[33] = file:/Users/freytag/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[34] = file:/Users/freytag/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[35] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-compiler/5.0.9/izpack-compiler-5.0.9.jar
[ERROR] urls[36] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-native/5.0.9/izpack-native-5.0.9.jar
[ERROR] urls[37] = file:/Users/freytag/.m2/repository/org/apache/maven/shared/maven-shared-jar/1.1/maven-shared-jar-1.1.jar
[ERROR] urls[38] = file:/Users/freytag/.m2/repository/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.jar
[ERROR] urls[39] = file:/Users/freytag/.m2/repository/org/apache/bcel/bcel/5.2/bcel-5.2.jar
[ERROR] urls[40] = file:/Users/freytag/.m2/repository/jakarta-regexp/jakarta-regexp/1.4/jakarta-regexp-1.4.jar
[ERROR] urls[41] = file:/Users/freytag/.m2/repository/commons-collections/commons-collections/3.1/commons-collections-3.1.jar
[ERROR] urls[42] = file:/Users/freytag/.m2/repository/org/apache/commons/commons-compress/1.3/commons-compress-1.3.jar
[ERROR] urls[43] = file:/Users/freytag/.m2/repository/jline/jline/2.12.1/jline-2.12.1.jar
[ERROR] urls[44] = file:/Users/freytag/.m2/repository/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar
[ERROR] urls[45] = file:/Users/freytag/.m2/repository/com/github/insubstantial/substance/7.3/substance-7.3.jar
[ERROR] urls[46] = file:/Users/freytag/.m2/repository/com/github/insubstantial/trident/7.3/trident-7.3-swing.jar
[ERROR] urls[47] = file:/Users/freytag/.m2/repository/com/github/insubstantial/laf-plugin/7.3/laf-plugin-7.3.jar
[ERROR] urls[48] = file:/Users/freytag/.m2/repository/com/github/insubstantial/laf-widget/7.3/laf-widget-7.3.jar
[ERROR] urls[49] = file:/Users/freytag/.m2/repository/com/incors/kunstoff-laf/2.0.2/kunstoff-laf-2.0.2.jar
[ERROR] urls[50] = file:/Users/freytag/.m2/repository/com/jgoodies/looks/2.2.2/looks-2.2.2.jar
[ERROR] urls[51] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-core/5.0.9/izpack-core-5.0.9.jar
[ERROR] urls[52] = file:/Users/freytag/.m2/repository/org/apache/ant/ant/1.9.4/ant-1.9.4.jar
[ERROR] urls[53] = file:/Users/freytag/.m2/repository/org/apache/ant/ant-launcher/1.9.4/ant-launcher-1.9.4.jar
[ERROR] urls[54] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-uninstaller/5.0.9/izpack-uninstaller-5.0.9.jar
[ERROR] urls[55] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-event/5.0.9/izpack-event-5.0.9.jar
[ERROR] urls[56] = file:/Users/freytag/.m2/repository/org/codehaus/izpack/izpack-api/5.0.9/izpack-api-5.0.9.jar
[ERROR] urls[57] = file:/Users/freytag/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : java.util.jar.Pack200
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :WoPeD-IzPack

**Comment by ChelloX** [comment]
Alles klar - klingt ja bis auf den einen Fehler so weit ganz gut.
Dieses Pack200 ist die Funktion IzPacks zum verkleinern der Jars. Warum hier Klassen fehlen kann ich auf Anhieb nicht. 
@NilsLeger könntest du dir das mal anschauen? Bin aktuell noch im Urlaub.

**Comment by NilsLeger** [comment]
@tfreytag @ChelloX 
Ich habe die Änderungen unter MacOS, Linux und Windows getestet. Auf allen drei OS läuft der Maven Install und die Anwendung lässt sich in der IDE ausführen.

Deshalb vermute ich, dass lediglich ein lokales Problem bei @tfreytag vorliegt.

Ich vermute, dass das verwendete JDK das Problem sein könnte. Ich verwende das adoptopenjdk-11.

**Comment by NilsLeger** [comment]
@tfreytag 
Jetzt fehlt laut meiner Liste noch eine Sache - die Anwendung direkt nach der Installation zu starten. Sie haben in Verbindung dazu gesagt, dass der JVM `-delay` übergeben werden muss. Diesen finde ich im alten Projekt auf Sourceforge allerdings nur in einer Datei: `runWoPeDonMac.sh`. Müssen wir hier überhaupt noch etwas anpassen?

**Comment by tfreytag** [comment]
Beim Mac-Installer klappt dieses Feature schon problemlos, das kann über ein Post-Install-Shellskript (runWoPeDonMac.sh) im PackageMaker eingestellt werden. Für Windows und Linux muss das in IZPack konfiguriert werden, weiß aber nicht genau wo man das macht. Funktioniert jetzt eigentlich auch der IZPack für Linux?

**Comment by tfreytag** [comment]
Ob man in Windows/Linux dafür den Schalter -delay braucht, muss noch geschaut werden, denn ggfs. fragt ja IZpack selbst in einem GUI-Dialog, ob man die gerade installierte Anwendung starten will oder nicht... Im einfachsten Fall kann dann einfach WoPeD direkt aufgerufen werden und man braucht weder das Shellskript noch den Schalter -delay (der zeigt ja im Grunde nur das Abfragefenster an bevor WoPeD losläuft und man kann es mit NEIN stoppen.

**Comment by NilsLeger** [comment]
Ich habe gerade recherchiert und es scheint keine _einfache_ Lösung zu geben, die Anwendung nach der Installation zu starten. Über ein Skript, das nach der Installation ausgeführt wird, scheint das jedoch möglich sein. Es stellt sich mir allerdings die Frage, wie viel Aufwand wir noch in die Installer stecken möchten. Ich finde es für jeden Nutzer absolut zumutbar die Anwendung nach der Installation selbst zu starten.

**Comment by tfreytag** [comment]
So schwierig hört sich diese Lösung aber nicht an: https://stackoverflow.com/questions/19721717/execute-script-after-installation-in-izpack. Ich glaube, so hatten wir das vorher auch gelöst, hat reibungslos unter Linux und Windows funktioniert.

**Comment by tfreytag** [comment]
Nach Umschalten auf Java 11 (warum klappt es nicht unter Java 14?) scheint der Build der Installer jetzt zu klappen. Leider kann ich die WoPeD-Installer.exe nicht starten, es kommt die Fehlermeldung "no bundled runtime ...". Wenn ich die WoPeD-Installer.jar starte, läuft es, aber die erzeugte WoPeD.exe hat das selbe Problem mit der bundled Runtime. Irgendwas scheint also mit dem Umwandeln von JAR in EXE schiefzugehen. Unter Linux kann ich den WoPeD-installer.jar starten, es wird auch ein Zielordner erzeugt, aber dort steht leider keine ausführbare Datei, nur die anderen Hilfsdateien sind dort drin.
Bildschirmfoto 2020-09-07 um 17 42 43

**Comment by NilsLeger** [comment]
Unter Java 14 funktioniert das nicht, da m. W. pack 200 aus dem JDK entfernt wurde.
Bei mir funktioniert der EXE Installer unter Windows, deshalb bin ich überfragt, wieso bei Ihnen diese Fehlermeldung auftritt.

Das Problem bei Linux ist mir auch schon aufgefallen und ich habe versucht, es zu beheben, bisher allerdings keine Lösung gefunden. Da es am Anfang der Umstellung auf maven jedoch schonmal funktioniert hat, finden wir dafür auf jeden Fall eine Lösung.

**Comment by tfreytag** [comment]
Die EXEs kann ich jetzt ausführen, es lag an einer inkorrekten Pfadangabe in JAVA_HOME in meiner (selten genutzten) Windows-Installation unter MacOS Parallels. Scheint jetzt also ok, bis auf den seltsamen Bug, dass bei der Sprachauswahl neben der deutschen Flagge nun ein serbokroatischer String steht (statt "Deutsch"). Ist das vielleicht mittlerweile gefixt von IZPack? Und es fehlt noch das Feature mit dem Post Install Skript.
Bzgl. Linux hoffen wir dann einfach auf eine baldige Lösung.

**Comment by ChelloX** [comment]
Der Installer für Linux läuft jetzt auch. Meiner Meinung nach wäre es an der Zeit diesen PR in den Master zu mergen.
Das Problem mit den falschen Flaggen bei der Installation hat sich nach einem Update von IzPack auch gelöst. 
@tfreytag Gerne testen und dann mergen.

**Comment by ChelloX** [comment]
Ich habe jetzt auch eine Funktion gefunden, um WoPeD während der Installation zu starten. Ist eine Standardfunktionalität von IzPack, welche aber nicht zu 100% zufriedenstellend ist. So wird WoPeD gestartet und in dem Fenster des Installationswizards muss noch 2x auf "Weiter" geklickt werden, um die Installation endgültig abzuschließen. 
@tfreytag Bitte einmal anschauen und deine Meinung dazu geben.

**Comment by tfreytag** [comment]
Installer auf Windows und Linux funktionieren, der auf MacOS ja sowieso schon. Schaut also gut aus. Kleinere kosmetische Verbesserungswünsche:
- Am Ende von Windows-IZPack Setup sollte WoPeD mit Schalter -delay aufgerufen werden, dann wird erst noch gefragt, ob man starten will oder nicht. Derzeit startet WoPeD unaufgefordert. Das Problem ist aber, dass die aus der JAR erzeugte EXE keine Kommandozeilen-Parameter übernehmen kann.
- Am Ende des Linux-IZPack Setup sollte das gleiche passieren. Derzeit wird da ja die JAR direkt mit Java gestartet (nach letzter Änderung von Nils) und da könnte der -delay Parameter mitgegeben werden - das funktioniert aber bei meiner Ubuntu wohl nicht...

Grundsätzlich wäre es schön, wenn die beiden IZPack-Installer m Ordner WoPeD-Installer/installers abgelegt würden mit der Namenskonvention WoPeD-install-windows-X_X_X.exe bzw. WoPeD-install-linux-X_X_X.jar. Da sind dann alle drei Installer an gut erkennbarer Stelle. 

Außerdem: Kann man die Fehlermeldungen in CommonLibs irgendwie wegkriegen? Da wird über nicht-existente Dependencies geklagt. 

Wie kann ich eigentlich die Deployment-Pipeline mit einem Mausklick starten? Derzeit muss ich wohl erst ins Maven-Panel gehen und dort nacheinander clean und install starten. Ist irgendwie unhandlich. 

Schöne Grüße

Thomas

**Comment by NilsLeger** [comment]
@tfreytag 
Der Autostart von WoPeD unter Linux funktioniert bei mir leider auch nicht - es tritt ein Berechtigungsproblem auf. Welcher Fehler tritt bei Dir auf?

@tfreytag 
Wenn wir den MR fertig haben, können wir beide uns zusammen setzen und einmal die Continuous Integration Pipeline durchspielen.

**Review by tfreytag — APPROVED** [review]

**Comment by tfreytag** [comment]
Geht klar

**Comment by tfreytag** [comment]
Linux Installer kann ich derzeit nicht testen, da in meinem Ubuntu der direkte Aufruf von JARs nicht klappt. Ich muss auf die Kommandozeile und von Hand "java -jar ..." eintippen, dann geht es, auch mit dem "-delay"-Parameter. Nervt, aber ich finde die Ursache nicht. Letztlich aber wohl kein IZPack Problem. 

Bin jetzt erst mal eine Woche verreist. Wir sollten uns vielleicht in der übernächsten Woche mal kurzschließen und die offenen Punkte durchgehen. Vorschlag: Montag 19.10. 13:00 h.

**Pull request merged**
